### ISSUE TITLE
Consider using pre-shared dictionary

### ISSUE THREAD

**Issue by PiotrSikora** [tlswg/certificate-compression#1]
[QUIC Crypto], which introduced idea of Certificate Compression, uses pre-shared dictionary that contains [common certificate substrings] (among other things).

During my unscientific [Brotli vs zlib] comparison, using  [common certificate substrings] from [QUIC Crypto] alone yields ~10% improvement for both: Brotli and zlib, for both: RSA and ECDSA certificate chains:

facebook.com certificate chain (ECDSA):

    facebook.com-ecdsa-chain.der 2024 (100%)

    facebook.com-ecdsa-chain.br1 1823 (90%) vs 1823 (90%) -> 0% smaller
    facebook.com-ecdsa-chain.br6 1673 (83%) vs 1505 (74%) -> 10% smaller
    facebook.com-ecdsa-chain.br9 1644 (81%) vs 1482 (73%) -> 10% smaller
    facebook.com-ecdsa-chain.brZ 1597 (79%) vs 1460 (72%) -> 9% smaller

    facebook.com-ecdsa-chain.gz1 1699 (84%) vs 1536 (76%) -> 10% smaller
    facebook.com-ecdsa-chain.gz6 1687 (83%) vs 1506 (74%) -> 11% smaller
    facebook.com-ecdsa-chain.gz9 1687 (83%) vs 1506 (74%) -> 11% smaller

google.com certificate chain (RSA):

    google.com-rsa-chain.der 2160 (100%)

    google.com-rsa-chain.br1 1541 (71%) vs 1541 (71%) -> 0% smaller
    google.com-rsa-chain.br6 1343 (62%) vs 1248 (58%) -> 7% smaller
    google.com-rsa-chain.br9 1348 (62%) vs 1239 (57%) -> 8% smaller
    google.com-rsa-chain.brZ 1330 (62%) vs 1233 (57%) -> 7% smaller

    google.com-rsa-chain.gz1 1434 (66%) vs 1317 (61%) -> 8% smaller
    google.com-rsa-chain.gz6 1398 (65%) vs 1266 (59%) -> 9% smaller
    google.com-rsa-chain.gz9 1398 (65%) vs 1266 (59%) -> 9% smaller

Perhaps we should consider bringing this feature to this draft?

cc @agl @vasilvv @ghedo 

[QUIC Crypto]: https://docs.google.com/document/d/1g5nIXAIkN_Y-7XJW5K45IblHd_L2f5LTaDUDwvZ5L6g/view
[common certificate substrings]: https://chromium.googlesource.com/chromium/src/+/19c30774eedcef459c776bde1c06e75bd48bf71e/net/quic/core/crypto/cert_compressor.cc#19
[Brotli vs zlib]: https://www.ietf.org/mail-archive/web/tls/current/msg23549.html

**Comment by ghedo** [comment]
FTR, thre were a couple of discussions about this at https://github.com/ghedo/tls-certificate-compression/issues/2 and on the [WG mailing list](https://www.ietf.org/mail-archive/web/tls/current/msg22537.html).

The consensus is that the dictionary would need to be CA neutral, which could impact the effectiveness of the dictionary itself, meaning that the QUIC dictionary would not be a viable option.

**Comment by ghedo** [comment]
Closing this since we decided to avoid dictionaries for now, and it will be possible to add additional compression code points for algorithm+dictionary if/when needed.
