### ISSUE TITLE
Compress Client Certificates

### ISSUE THREAD

**Issue by PiotrSikora** [tlswg/certificate-compression#2]
As [suggested on the mailing list](https://www.ietf.org/mail-archive/web/tls/current/msg23546.html), please consider also compressing Client Certificates.

cc @vasilvv @ghedo

**Comment by ghedo** [comment]
FTR, thre were a couple of discussions about this at https://github.com/ghedo/tls-certificate-compression/issues/2 and on the [WG mailing list](https://www.ietf.org/mail-archive/web/tls/current/msg22537.html).

The consensus is that the dictionary would need to be CA neutral, which could impact the effectiveness of the dictionary itself.

**Comment by ghedo** [comment]
Fixed in 00730f03a701efc2d678f047531649bed79011e2.
