### ISSUE TITLE
I-D nits: Downref: Normative reference to an Informational RFC

### ISSUE THREAD

**Issue by ghedo** [tlswg/certificate-compression#22]
When running idnits, it reports a couple of issues:
```
  Checking references for intended status: Proposed Standard
  ----------------------------------------------------------------------------

     (See RFCs 3967 and 4897 for information about using normative references
     to lower-maturity documents in RFCs)

  ** Downref: Normative reference to an Informational RFC: RFC 1950

  ** Downref: Normative reference to an Informational RFC: RFC 7932


     Summary: 2 errors (**), 0 flaws (~~), 0 warnings (==), 0 comments (--).
```

RFC1950 and RfC7932 are the zlib and brotli RFCs. I'm guessing the way to fix this would to remove the related MUSTs and downgrade the references, though I haven't come up with appropriate wording yet.

/cc @seanturner (any suggestion?)

**Comment by ghedo** [comment]
#21 fixes a couple more errors that are not listed here btw.

**Comment by seanturner** [comment]
Note that downref "nits" can be handled via documented procedures in [RFC 3967](https://datatracker.ietf.org/doc/rfc3967/).  In summary, we can identify them in the IETF LC (when we get there) and see who objects to referring to an informative RFC from this draft, which is intended for standards track.  For zlib there are a ton of these already and it looks like somebody just didn't update the downref registry (i.e., I suspect there will be no strenuous objections from anybody).  For brotli, it's newer but I am not too worried about the uproar.  I'd just leave the MUST and the normative references in.

**Comment by ghedo** [comment]
Ok, thanks @seanturner, I'll close this then.
